'''
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
'''

def findTheDifference(s, t):
	result = 0
	for char in s:
		result ^= ord(char)
	for char in t:
		result ^= ord(char)
	return chr(result)

s = "abcd", t = "abcde"
print(findTheDifference(s,t))
